import SwiftUI
import CoreGraphics

/// A print-ready packing list. Always light — a PDF isn't theme-aware — but it
/// keeps the Suite type ramp and amber accent.
struct PackingListDocument: View {
    struct Section: Identifiable {
        let title: String
        let rows: [Row]
        var id: String { title }
    }
    struct Row: Identifiable {
        let name: String
        let quantity: Int
        let packed: Bool
        var id: String { name }
    }

    let title: String
    let subtitle: String
    let sections: [Section]
    let packedCount: Int
    let totalCount: Int

    private let ink = Color(hex: 0x0A0A0A)
    private let sub = Color(hex: 0x77736C)
    private let hair = Color(hex: 0xE2DED7)
    private let accent = Color(hex: 0xD09A42)

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            HStack(alignment: .firstTextBaseline) {
                Text("Suite").font(.archivo(20, .heavy)).foregroundStyle(ink)
                + Text(".").font(.archivo(20, .heavy)).foregroundStyle(accent)
                Spacer()
                Text("PACKING LIST")
                    .font(.jetBrainsMono(10)).tracking(2)
                    .foregroundStyle(sub)
            }
            .padding(.bottom, 22)

            Text(title).font(.archivo(26, .bold)).tracking(26 * -0.02).foregroundStyle(ink)
            Text(subtitle).font(.jetBrainsMono(11)).foregroundStyle(sub).padding(.top, 6)

            Text("\(packedCount) of \(totalCount) packed")
                .font(.archivo(13, .semibold)).foregroundStyle(accent)
                .padding(.top, 12)

            Rectangle().fill(hair).frame(height: 1).padding(.vertical, 20)

            ForEach(sections) { section in
                Text(section.title.uppercased())
                    .font(.jetBrainsMono(10)).tracking(1.6).foregroundStyle(sub)
                    .padding(.bottom, 8)
                ForEach(section.rows) { row in
                    HStack(spacing: 12) {
                        RoundedRectangle(cornerRadius: 4)
                            .stroke(row.packed ? accent : hair, lineWidth: 1.5)
                            .background(RoundedRectangle(cornerRadius: 4).fill(row.packed ? accent : .clear))
                            .frame(width: 16, height: 16)
                            .overlay {
                                if row.packed {
                                    Image(systemName: "checkmark")
                                        .font(.system(size: 9, weight: .bold))
                                        .foregroundStyle(.white)
                                }
                            }
                        Text(row.quantity > 1 ? "\(row.name)  ×\(row.quantity)" : row.name)
                            .font(.archivo(13))
                            .strikethrough(row.packed, color: sub)
                            .foregroundStyle(row.packed ? sub : ink)
                        Spacer()
                    }
                    .frame(height: 26)
                }
                Spacer().frame(height: 18)
            }

            Spacer(minLength: 0)

            Text("Generated by Suite · \(Date.now.formatted(date: .abbreviated, time: .omitted))")
                .font(.jetBrainsMono(9)).foregroundStyle(sub)
                .padding(.top, 12)
        }
        .padding(44)
        .frame(width: 595, alignment: .topLeading)   // A4 width in points
        .background(Color(hex: 0xFDFCFA))
    }

    // MARK: builders

    static func from(trip: Trip) -> PackingListDocument {
        let items = trip.suitcases.first?.items ?? []
        let grouped = Dictionary(grouping: items, by: \.category)
        let sections = ItemCategory.allCases
            .sorted { $0.sortRank < $1.sortRank }
            .compactMap { cat -> Section? in
                guard let list = grouped[cat], !list.isEmpty else { return nil }
                let rows = list.sorted { $0.sortOrder < $1.sortOrder }
                    .map { Row(name: $0.name, quantity: $0.quantity, packed: $0.isPacked) }
                return Section(title: cat.displayName, rows: rows)
            }
        let place = [trip.destinationCity, trip.destinationCountry].filter { !$0.isEmpty }.joined(separator: ", ")
        return PackingListDocument(
            title: trip.name,
            subtitle: [PackingChecklistView.dateRange(trip), place].filter { !$0.isEmpty }.joined(separator: " · "),
            sections: sections,
            packedCount: items.filter(\.isPacked).count,
            totalCount: items.count)
    }

    static let sample = PackingListDocument(
        title: "Lisbon & Sintra",
        subtitle: "15–21 Sep 2026 · Lisbon, Portugal",
        sections: [
            Section(title: "Documents", rows: [
                Row(name: "Passport", quantity: 1, packed: true),
                Row(name: "Travel insurance card", quantity: 1, packed: false)]),
            Section(title: "Clothing", rows: [
                Row(name: "Linen shirts", quantity: 3, packed: true),
                Row(name: "Swim shorts", quantity: 2, packed: true),
                Row(name: "Walking shoes", quantity: 1, packed: false)]),
            Section(title: "Electronics", rows: [
                Row(name: "Chargers", quantity: 2, packed: false)]),
        ],
        packedCount: 4, totalCount: 21)
}

/// Renders a `PackingListDocument` to a single-page PDF in the temp directory.
@MainActor
func makePackingListPDF(_ document: PackingListDocument, name: String) -> URL? {
    let renderer = ImageRenderer(content: document)
    renderer.proposedSize = ProposedViewSize(width: 595, height: nil)

    let safe = name.replacingOccurrences(of: "/", with: "-")
    let url = FileManager.default.temporaryDirectory
        .appendingPathComponent("\(safe.isEmpty ? "Packing list" : safe).pdf")

    var page = CGRect(x: 0, y: 0, width: 595, height: 842)
    var ok = false
    renderer.render { size, draw in
        page.size = CGSize(width: size.width, height: max(size.height, 842))
        guard let ctx = CGContext(url as CFURL, mediaBox: &page, nil) else { return }
        ctx.beginPDFPage(nil)
        draw(ctx)
        ctx.endPDFPage()
        ctx.closePDF()
        ok = true
    }
    return ok ? url : nil
}
